/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        brand: {
          primary: '#124C35',
          dark: '#082A1D',
          soft: '#DCEAE2',
          cream: '#F1F0E9',
          saffron: '#C87B25',
          sky: '#397EAC',
          teal: '#0F766E',
          purple: '#6D4AA2',
          rose: '#B44568',
          amber: '#C48716',
          sage: '#6F927C',
          mist: '#E8F0EA',
          aqua: '#5D9E9A',
          lavender: '#8B78A8',
          peach: '#D89A76',
          success: '#18734B',
          warning: '#B96F17',
          error: '#B13D3D',
          text: '#152019',
          muted: '#58665D',
          card: '#FBFCFA',
          border: '#D4DED7',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Inter', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        soft: '0 2px 8px -2px rgba(8,42,29,0.10), 0 4px 16px -4px rgba(8,42,29,0.07)',
        card: '0 1px 3px rgba(8,42,29,0.07), 0 1px 2px rgba(8,42,29,0.05)',
        lift: '0 8px 24px -8px rgba(8,42,29,0.16), 0 4px 12px -4px rgba(8,42,29,0.10)',
      },
      borderRadius: {
        'xl': '14px',
        '2xl': '20px',
        '3xl': '28px',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.4s ease-out',
        'slide-in-right': 'slideInRight 0.3s ease-out',
        'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
        'shimmer': 'shimmer 1.5s linear infinite',
        'scale-in': 'scaleIn 0.2s ease-out',
        'float-soft': 'floatSoft 3.5s ease-in-out infinite',
        'calm-float': 'calmFloat 5.5s ease-in-out infinite',
        'soft-glow': 'softGlow 4s ease-in-out infinite',
        'gentle-pop': 'gentlePop 0.42s cubic-bezier(0.22,1,0.36,1)',
        'route-reveal': 'routeReveal 0.32s ease-out both',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp: { '0%': { opacity: '0', transform: 'translateY(12px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideInRight: { '0%': { opacity: '0', transform: 'translateX(20px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        pulseSoft: { '0%,100%': { opacity: '1' }, '50%': { opacity: '0.6' } },
        shimmer: { '0%': { backgroundPosition: '-1000px 0' }, '100%': { backgroundPosition: '1000px 0' } },
        scaleIn: { '0%': { opacity: '0', transform: 'scale(0.95)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        floatSoft: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-3px)' } },
        calmFloat: { '0%,100%': { transform: 'translate3d(0,0,0)' }, '50%': { transform: 'translate3d(0,-6px,0)' } },
        softGlow: { '0%,100%': { opacity: '0.45', transform: 'scale(1)' }, '50%': { opacity: '0.75', transform: 'scale(1.06)' } },
        gentlePop: { '0%': { opacity: '0', transform: 'translateY(10px) scale(0.985)' }, '100%': { opacity: '1', transform: 'translateY(0) scale(1)' } },
        routeReveal: { '0%': { opacity: '0', transform: 'translateY(8px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
      },
    },
  },
  plugins: [],
}
